{{- include "common.values.setup" . -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}-config
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  {{- $files := .Files }}
  {{- range $cm := .Values.configmap }}
  {{ $cm.filename }}: |-
  
{{ $files.Get $cm.path | indent 4 }}
  {{- end }}
