version: "3.9"
services:
  goamd:
    image: ipedrazas/gobuild:v1.0.0-amd64
    volumes:
    - __WORKSPACE__/__NAME__:/workspace # workspace
    environment:
    - GOOS=linux
    - GOARCH=amd64
    - CGO_ENABLED=0
    working_dir: /workspace
    command: go build -ldflags '-extldflags "-static"' -o dist/amd64/__NAME__
  
  goarm:
    image: ipedrazas/gobuild:v1.0.0-arm64
    volumes:
    - __WORKSPACE__/__NAME__:/workspace # workspace
    environment:
    - GOOS=linux
    - GOARCH=arm64
    - CGO_ENABLED=0
    working_dir: /workspace
    command: go build -ldflags '-extldflags "-static"'  -o dist/arm64/__NAME__
