version: "3.9"
services:
  createOAM:
    image: harbor.alacasa.uk/library/k8stools:latest
    volumes:
      - __WORKSPACE__:/workspace # workspace
    working_dir: "/workspace"
    command: ["/workspace/gp/targets/oam/process.sh"]